"""DimSymbolsWriter: MERGE into dim_symbols + auto-mark removals."""

from __future__ import annotations

import logging
from dataclasses import dataclass

import pandas as pd
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

from yfinance_bigquery.schema import DIM_SYMBOLS_SCHEMA, SP500_MEMBERSHIP_SCHEMA

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class DimSymbolsTableRef:
    project: str
    dataset: str
    table: str

    @classmethod
    def parse(cls, fq: str) -> DimSymbolsTableRef:
        parts = fq.split(".")
        if len(parts) != 3:
            raise ValueError(f"expected project.dataset.table, got {fq!r}")
        return cls(*parts)

    def __str__(self) -> str:
        return f"{self.project}.{self.dataset}.{self.table}"


class DimSymbolsWriter:
    def __init__(self, client: bigquery.Client) -> None:
        self.client = client

    def create_table_if_missing(self, ref: DimSymbolsTableRef) -> None:
        try:
            self.client.get_table(str(ref))
            return
        except NotFound:
            pass
        # Build schema from DIM_SYMBOLS_SCHEMA (see schema.py)
        bq_schema = [
            bigquery.SchemaField(c.name, c.type, mode=c.mode,
                                 description=c.short_description)
            for c in DIM_SYMBOLS_SCHEMA
        ]
        table = bigquery.Table(str(ref), schema=bq_schema)
        table.description = (
            "S&P 500 constituent dimension table. Sourced from Wikipedia. "
            "Generated by yfinance-bigquery."
        )
        self.client.create_table(table)
        log.info("created table %s", ref)

    def merge(
        self, *, ref: DimSymbolsTableRef, constituents: pd.DataFrame,
    ) -> int:
        """MERGE upsert; auto-mark date_removed for active rows no longer in source.

        Returns number of rows in `constituents`.
        """
        if len(constituents) == 0:
            log.warning("empty constituents DataFrame; skipping merge")
            return 0

        # Load constituents into a TEMP-like staging via load_table_from_dataframe to a
        # session-scoped temp table is complex; simpler: build the MERGE source as inline
        # SQL using ARRAY of STRUCT.
        rows_sql = ", ".join(
            f"STRUCT('{r[0]}' AS symbol, "
            f"{_sql_str(r[1])} AS name, "
            f"{_sql_str(r[2])} AS sector, "
            f"{_sql_str(r[3])} AS industry, "
            f"{_sql_date(r[4])} AS date_added)"
            for r in constituents[
                ["symbol", "name", "sector", "industry", "date_added"]
            ].itertuples(index=False, name=None)
        )
        merge_sql = (
            f"MERGE INTO `{ref}` t USING (SELECT * FROM UNNEST([{rows_sql}])) s\n"
            "ON t.symbol = s.symbol\n"
            "WHEN MATCHED THEN UPDATE SET\n"
            "  name = s.name, sector = s.sector, industry = s.industry,\n"
            "  date_added = COALESCE(s.date_added, t.date_added),\n"
            "  last_refreshed_at = CURRENT_TIMESTAMP()\n"
            "WHEN NOT MATCHED THEN INSERT\n"
            "  (symbol, name, sector, industry, date_added, last_refreshed_at)\n"
            "  VALUES (s.symbol, s.name, s.sector, s.industry, s.date_added, "
            "CURRENT_TIMESTAMP());"
        )
        self.client.query_and_wait(merge_sql)

        # Mark removals: any active row not in constituents → set date_removed = today
        active_symbols = ", ".join(f"'{s}'" for s in constituents["symbol"])
        removal_sql = (
            f"UPDATE `{ref}` SET date_removed = CURRENT_DATE() "
            f"WHERE date_removed IS NULL AND symbol NOT IN ({active_symbols});"
        )
        self.client.query_and_wait(removal_sql)

        return len(constituents)


def _is_na(v: object) -> bool:
    """Return True if v is None or a pandas NA scalar."""
    if v is None:
        return True
    try:
        result = pd.isna(v)  # type: ignore[arg-type]
        return bool(result)
    except (TypeError, ValueError):
        return False


def _sql_str(v: object) -> str:
    if _is_na(v):
        return "NULL"
    return "'" + str(v).replace("'", "\\'") + "'"


def _sql_date(v: object) -> str:
    if _is_na(v):
        return "NULL"
    return f"DATE '{v}'"


class MembershipWriter:
    """Write the point-in-time membership table via full truncate+load.

    Membership is a complete reconstruction on every run (not an incremental
    upsert), so a write-truncate load is correct — no MERGE.
    """

    def __init__(self, client: bigquery.Client) -> None:
        self.client = client

    def create_table_if_missing(self, ref: DimSymbolsTableRef) -> None:
        try:
            self.client.get_table(str(ref))
            return
        except NotFound:
            pass
        bq_schema = [
            bigquery.SchemaField(c.name, c.type, mode=c.mode,
                                 description=c.short_description)
            for c in SP500_MEMBERSHIP_SCHEMA
        ]
        table = bigquery.Table(str(ref), schema=bq_schema)
        table.description = (
            "Point-in-time S&P 500 membership spells (survivorship-bias-free), "
            "reconstructed from Wikipedia by yfinance-bigquery."
        )
        self.client.create_table(table)
        log.info("created table %s", ref)

    def replace(self, *, ref: DimSymbolsTableRef, membership: pd.DataFrame) -> int:
        """Full-replace the membership table. Returns rows written."""
        if len(membership) == 0:
            log.warning("empty membership DataFrame; skipping replace")
            return 0
        self.create_table_if_missing(ref)
        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
            schema=[
                bigquery.SchemaField(c.name, c.type, mode=c.mode)
                for c in SP500_MEMBERSHIP_SCHEMA
            ],
        )
        job = self.client.load_table_from_dataframe(
            membership, str(ref), job_config=job_config
        )
        job.result()
        log.info("wrote %d membership rows to %s", len(membership), ref)
        return len(membership)
