"""OHLCVWriter: idempotent INSERT for per-interval OHLCV tables.

Also exports ``_iter_chunks`` — the date-range partitioner used by the CLI.
Supported chunk kinds: "year" / "month" / "week" / "range".
"""

from __future__ import annotations

import calendar
import logging
from dataclasses import dataclass
from datetime import date, datetime, timedelta

import pandas as pd
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

from yfinance_bigquery.intervals import Interval
from yfinance_bigquery.schema import OHLCV_SCHEMA, get_ohlcv_clustering, get_ohlcv_partitioning

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Table reference
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class OHLCVTableRef:
    project: str
    dataset: str
    table: str

    @classmethod
    def parse(cls, fq: str) -> OHLCVTableRef:
        parts = fq.split(".")
        if len(parts) != 3:
            raise ValueError(f"expected project.dataset.table, got {fq!r}")
        return cls(*parts)

    def __str__(self) -> str:
        return f"{self.project}.{self.dataset}.{self.table}"


# ---------------------------------------------------------------------------
# Schema helpers
# ---------------------------------------------------------------------------


def _bq_schema_from_specs() -> list[bigquery.SchemaField]:
    """Convert OHLCV_SCHEMA ColumnSpec list to BigQuery SchemaField objects."""
    return [
        bigquery.SchemaField(
            name=spec.name,
            field_type=spec.type,
            mode=spec.mode,
            description=spec.short_description,
        )
        for spec in OHLCV_SCHEMA
    ]


def _coerce_df_to_schema(df: pd.DataFrame) -> pd.DataFrame:
    """Coerce DataFrame column dtypes so pyarrow can convert into the BQ schema.

    INT64 columns are cast to pandas nullable Int64; STRING columns to pandas
    string dtype. This prevents pyarrow type-mismatch errors when yfinance
    returns columns with unexpected dtypes (e.g. float64 volume for all-null
    rows, or object dtype for string columns).
    """
    for spec in OHLCV_SCHEMA:
        if spec.name not in df.columns:
            continue
        if spec.type == "INT64":
            df[spec.name] = df[spec.name].astype("Int64")
        elif spec.type == "STRING":
            df[spec.name] = df[spec.name].astype("string")
    return df


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------


class OHLCVWriter:
    """Idempotent writer for a single per-interval OHLCV BigQuery table.

    The ``interval`` is bound at construction so the writer knows the partition
    granularity (DAY vs MONTH) for table creation without caller guesswork.
    """

    def __init__(self, client: bigquery.Client, interval: Interval) -> None:
        self.client = client
        self.interval = interval

    def create_table_if_missing(self, ref: OHLCVTableRef) -> None:
        """Create the OHLCV table with partitioning + clustering if absent."""
        try:
            self.client.get_table(str(ref))
            log.debug("table %s exists; skipping create", ref)
            return
        except NotFound:
            pass

        partitioning = get_ohlcv_partitioning(self.interval)
        clustering = get_ohlcv_clustering()

        table = bigquery.Table(str(ref), schema=_bq_schema_from_specs())
        table.time_partitioning = bigquery.TimePartitioning(
            type_=partitioning.type,
            field=partitioning.field,
        )
        table.clustering_fields = clustering
        table.description = (
            f"yfinance OHLCV bars at {self.interval.value} interval. "
            "Source: Yahoo Finance via yfinance. "
            "Generated by yfinance-bigquery."
        )
        self.client.create_table(table)
        log.info("created table %s", ref)

    def write(
        self,
        ref: OHLCVTableRef,
        df: pd.DataFrame,
        start: str,
        end: str,
    ) -> int:
        """Write ``df`` for [start, end] idempotently (DELETE-then-INSERT).

        Parameters
        ----------
        ref:
            Fully-qualified BigQuery table reference.
        df:
            DataFrame of OHLCV rows. Must contain 'symbol' and 'trading_date'.
        start:
            ISO date string (inclusive) for the DELETE window.
        end:
            ISO date string (inclusive) for the DELETE window.

        Returns
        -------
        int
            Number of rows written (0 if df is empty).
        """
        if len(df) == 0:
            log.info("empty dataframe; skip write to %s", ref)
            return 0

        symbols = df["symbol"].unique().tolist()

        delete_sql = (
            f"DELETE FROM `{ref}` "
            f"WHERE trading_date BETWEEN @start AND @end "
            f"AND symbol IN UNNEST(@symbols)"
        )
        params = [
            bigquery.ScalarQueryParameter("start", "DATE", start),
            bigquery.ScalarQueryParameter("end", "DATE", end),
            bigquery.ArrayQueryParameter("symbols", "STRING", symbols),
        ]
        job_config = bigquery.QueryJobConfig(query_parameters=params)
        log.info(
            "DELETE %s where trading_date BETWEEN %s AND %s AND symbol IN %s",
            ref, start, end, symbols,
        )
        self.client.query_and_wait(delete_sql, job_config=job_config)

        log.info("INSERT %d rows -> %s", len(df), ref)
        load_job_config = bigquery.LoadJobConfig(
            schema=_bq_schema_from_specs(),
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            source_format=bigquery.SourceFormat.PARQUET,
        )
        df = _coerce_df_to_schema(df)
        self.client.load_table_from_dataframe(
            df, str(ref), job_config=load_job_config
        ).result()
        return len(df)


# ---------------------------------------------------------------------------
# Chunk iterator
# ---------------------------------------------------------------------------


def _iter_chunks(start: str, end: str, kind: str) -> list[tuple[str, str]]:
    """Split [start, end] into date chunks.

    Supported kinds
    ---------------
    "year"
        One chunk per calendar year (Jan 1 – Dec 31, clipped to [start, end]).
    "month"
        One chunk per calendar month (1st – last day, clipped to [start, end]).
    "week"
        7-day chunks starting from ``start``, clipped to ``end``.
        E.g. 2024-02-15 → 2024-03-05 yields
        (2024-02-15, 2024-02-21), (2024-02-22, 2024-02-28), (2024-02-29, 2024-03-05).
    "range"
        Single chunk covering the entire [start, end] range.
    """
    s = datetime.strptime(start, "%Y-%m-%d").date()
    e = datetime.strptime(end, "%Y-%m-%d").date()
    if kind == "range":
        return [(s.isoformat(), e.isoformat())]
    chunks: list[tuple[str, str]] = []
    cur = s
    while cur <= e:
        if kind == "year":
            period_end = date(cur.year, 12, 31)
        elif kind == "month":
            last_day = calendar.monthrange(cur.year, cur.month)[1]
            period_end = date(cur.year, cur.month, last_day)
        elif kind == "week":
            period_end = cur + timedelta(days=6)
        else:
            raise ValueError(f"unknown chunk kind: {kind!r}")
        last = min(period_end, e)
        chunks.append((cur.isoformat(), last.isoformat()))
        cur = last + timedelta(days=1)
    return chunks
