"""Render OHLCV_SCHEMA + curated content into 5 formats: BQ descriptions, LLM
markdown, data-dictionary JSON, hobbyist markdown, dbt YAML."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from google.cloud import bigquery

from yfinance_bigquery._version import __version__
from yfinance_bigquery.docs.taxonomy import SEMANTIC_GROUPS
from yfinance_bigquery.intervals import INTERVAL_CONFIG, Interval
from yfinance_bigquery.schema import OHLCV_SCHEMA, ColumnSpec


def render_bq_descriptions() -> list[bigquery.SchemaField]:
    """Return BigQuery SchemaField list with descriptions populated.

    Used by OHLCVWriter at table-create time and by ``yfinance-bigquery docs --format bq-apply``.
    OHLCV_SCHEMA is common across all 5 per-interval tables; apply this single
    SchemaField list to whichever table is being created or updated.
    """
    return [
        bigquery.SchemaField(
            name=c.name,
            field_type=c.type,
            mode=c.mode,
            description=c.short_description,
        )
        for c in OHLCV_SCHEMA
    ]


def render_data_dictionary(dataset: str, table: str) -> list[dict[str, Any]]:
    """Return JSON-serializable rows shaped like ``shared_ops.data_dictionary``."""
    now = datetime.now(timezone.utc).isoformat()  # noqa: UP017
    return [
        {
            "dataset": dataset,
            "table": table,
            "column": c.name,
            "dtype": c.type,
            "description": c.short_description,
            "business_definition": c.business_definition,
            "owner": "data-eng",
            "tags": list(c.semantic_tags),
            "source_system": "yfinance",
            "upstream_lineage_json": (
                f'{{"library": "yfinance-bigquery", '
                f'"version": "{__version__}", '
                f'"yfinance_field": "{c.yfinance_source_field}"}}'
            ),
            "created_at": now,
            "updated_at": now,
        }
        for c in OHLCV_SCHEMA
    ]


def render_llm_context() -> str:
    """One-file prompt-friendly markdown for LLM agents."""
    parts: list[str] = ["# yfinance OHLCV for LLMs", ""]
    parts.append(f"_Generated by yfinance-bigquery v{__version__}._\n")
    parts.append(
        "This document describes the per-interval `ohlcv_*` tables — OHLCV price bars "
        "for S&P 500 constituents ingested via yfinance. Use it as system-prompt context "
        "when generating SQL against these tables.\n"
    )

    parts.append("## Column reference\n")
    by_group = _columns_by_group()
    for group, label in SEMANTIC_GROUPS.items():
        cols = by_group.get(group, [])
        if not cols:
            continue
        parts.append(f"### {group} — {label}\n")
        for c in cols:
            parts.append(f"- **`{c.name}`** ({c.type}): {c.business_definition}")
            if c.gotchas:
                parts.append(f"  - Gotchas: {'; '.join(c.gotchas)}")
        parts.append("")

    parts.append("## OHLCV invariants\n")
    parts.append(
        "The ingestion pipeline's `InternalConsistencyVerifier` enforces these rules "
        "on every batch write. Rows violating them are flagged and excluded:\n"
    )
    invariants = [
        "`high >= max(open, close)` — the bar high must be the period's true maximum.",
        "`low <= min(open, close)` — the bar low must be the period's true minimum.",
        "`volume >= 0` or NULL — negative share counts are rejected.",
        "No future bars — `bar_start_utc` must be <= pipeline run time.",
        "No weekend bars for `1d` interval — equity markets are closed Saturday/Sunday.",
        "No duplicate bars — (symbol, bar_start_utc, interval) is a unique key; "
        "re-ingestion uses DELETE+INSERT to avoid duplicates.",
    ]
    for inv in invariants:
        parts.append(f"- {inv}")
    parts.append("")

    parts.append("## Tables by interval\n")
    parts.append(
        "Each interval has its own partitioned table. Use `trading_date` in WHERE "
        "clauses to exploit partition pruning.\n"
    )
    parts.append("| Table | Interval | Partition | Retention |")
    parts.append("|---|---|---|---|")
    for iv in Interval:
        cfg = INTERVAL_CONFIG[iv]
        retention = (
            f"{cfg.retention_days} days" if cfg.retention_days is not None else "unlimited"
        )
        parts.append(
            f"| `ohlcv_{iv.value}` | {iv.value} | {cfg.partition_granularity} | {retention} |"
        )
    parts.append("")
    parts.append(
        "Companion tables:\n"
        "- `dim_symbols` — S&P 500 universe (symbol, name, sector, industry, date_added, "
        "date_removed). Join key: `symbol`.\n"
        "- `_yfinance_ingest_runs` — pipeline run audit log (run_id, interval, "
        "symbol_count, bar_count, started_at, finished_at, status)."
    )
    parts.append("")

    return "\n".join(parts)


def render_markdown() -> str:
    """Hobbyist-friendly schema reference markdown."""
    parts: list[str] = ["# ohlcv_* schema\n"]
    parts.append(f"_Generated by yfinance-bigquery v{__version__}._\n")
    parts.append(
        "Per-interval OHLCV price bars for S&P 500 constituents. "
        "Schema is identical across all five interval tables.\n"
    )

    by_group = _columns_by_group()
    for group, label in SEMANTIC_GROUPS.items():
        cols = by_group.get(group, [])
        if not cols:
            continue
        parts.append(f"## {group}\n")
        parts.append(f"_{label}_\n")
        parts.append("| Column | Type | Mode | Description |")
        parts.append("|---|---|---|---|")
        for c in cols:
            parts.append(f"| `{c.name}` | {c.type} | {c.mode} | {c.short_description} |")
        parts.append("")

    return "\n".join(parts)


def render_dbt_yaml(model_name: str = "ohlcv_1d") -> str:
    """dbt model YAML with column descriptions and basic tests for required columns."""
    parts: list[str] = ["version: 2\n", "models:"]
    parts.append(f"  - name: {model_name}")
    parts.append("    description: |")
    parts.append("      Per-interval OHLCV price bars ingested via yfinance-bigquery.")
    parts.append("      Source: Yahoo Finance via yfinance library.")
    parts.append("    columns:")
    for c in OHLCV_SCHEMA:
        parts.append(f"      - name: {c.name}")
        parts.append("        description: |")
        parts.append(f"          {c.short_description}")
        if c.mode == "REQUIRED":
            parts.append("        tests:")
            parts.append("          - not_null")
    return "\n".join(parts) + "\n"


def apply_data_dictionary(
    *,
    client: bigquery.Client,
    dictionary_table: str,
    dataset: str,
    table: str,
) -> int:
    """Atomically replace the data_dictionary rows for (dataset, table).

    Wraps DELETE + INSERT in a single BEGIN TRANSACTION ... COMMIT TRANSACTION
    multi-statement query so the table is never observed in a half-replaced state.

    Returns the number of rows inserted.
    """
    rows = render_data_dictionary(dataset=dataset, table=table)
    if not rows:
        return 0

    # Build VALUES tuples inline. ~14 rows per table; well within DML limits.
    # Strings are escaped via repr-then-strip; tags is BQ array literal.
    def _str(s: str | None) -> str:
        if s is None:
            return "NULL"
        # BQ Standard SQL accepts backslash-escaped string literals.
        # Escape backslashes first, then single quotes, to avoid double-processing.
        return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"

    def _tags(t: list[str]) -> str:
        return "[" + ", ".join(_str(x) for x in t) + "]"

    values_lines: list[str] = []
    for r in rows:
        values_lines.append(
            "("
            f"{_str(r['dataset'])}, {_str(r['table'])}, {_str(r['column'])}, "
            f"{_str(r['dtype'])}, {_str(r['description'])}, "
            f"{_str(r['business_definition'])}, {_str(r['owner'])}, "
            f"{_tags(r['tags'])}, {_str(r['source_system'])}, "
            f"{_str(r['upstream_lineage_json'])}, "
            f"TIMESTAMP({_str(r['created_at'])}), TIMESTAMP({_str(r['updated_at'])})"
            ")"
        )
    values_sql = ",\n  ".join(values_lines)

    sql = (
        "BEGIN TRANSACTION;\n"
        f"DELETE FROM `{dictionary_table}` "
        f"WHERE dataset=@dataset AND table=@table;\n"
        f"INSERT INTO `{dictionary_table}` "
        "(dataset, `table`, column, dtype, description, business_definition, "
        "owner, tags, source_system, upstream_lineage_json, created_at, updated_at) "
        f"VALUES\n  {values_sql};\n"
        "COMMIT TRANSACTION;"
    )
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("dataset", "STRING", dataset),
            bigquery.ScalarQueryParameter("table", "STRING", table),
        ]
    )
    client.query_and_wait(sql, job_config=job_config)
    return len(rows)


def _columns_by_group() -> dict[str, list[ColumnSpec]]:
    """Group columns by their first semantic_tag (canonical group)."""
    out: dict[str, list[ColumnSpec]] = {}
    for c in OHLCV_SCHEMA:
        if not c.semantic_tags:
            continue
        out.setdefault(c.semantic_tags[0], []).append(c)
    return out
